name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          uv-version: "0.6.6"
          python-version: "3.12"

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish --trusted-publishing always
